# Generated by Django 4.2.2 on 2023-06-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
