# Generated by Django 4.2 on 2023-06-28 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_cart_delete_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='home.menu'),
        ),
    ]
