# Generated by Django 4.2 on 2023-06-29 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_menu_in_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
