# Generated by Django 4.2 on 2023-07-02 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_delete_cart_delete_menu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='otp',
        ),
    ]
