# Generated by Django 4.2 on 2023-07-03 08:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Menu', '0004_remove_menu_in_cart_remove_menu_quantity'),
        ('Cart', '0004_alter_cart_items_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart_items',
            unique_together={('user', 'item')},
        ),
    ]
