# Generated by Django 4.2 on 2023-07-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0005_alter_cart_items_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_items',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
