# Generated by Django 4.2 on 2023-07-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0006_alter_cart_items_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_items',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
