# Generated by Django 4.2 on 2023-07-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0008_alter_cart_items_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_items',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
