# Generated by Django 4.2 on 2023-07-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0010_order_alter_cart_items_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_items',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
