# Generated by Django 4.2 on 2023-07-10 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0009_remove_menu_in_cart_remove_menu_quantity'),
        ('Cart', '0011_alter_cart_items_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_items',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu', to='Menu.menu'),
        ),
    ]
