# Generated by Django 4.2 on 2023-07-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0012_alter_cart_items_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_option',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
