# Generated by Django 4.2 on 2023-07-12 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0015_dinning_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinning_info',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cart.order'),
        ),
    ]
