# Generated by Django 4.2 on 2023-07-16 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0017_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery_address',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dinning_info',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='delivery_address',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cart.customer'),
        ),
        migrations.AddField(
            model_name='dinning_info',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cart.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cart.customer'),
        ),
    ]
