# Generated by Django 4.2 on 2023-07-17 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0021_order_razorpay_order_id_order_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
