# Generated by Django 4.2 on 2023-07-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0002_delete_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
