# Generated by Django 4.2 on 2023-07-03 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0003_menu_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='in_cart',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='quantity',
        ),
    ]
