# Generated by Django 4.2 on 2023-07-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0006_alter_menu_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='quantity',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
