# Generated by Django 5.2.6 on 2026-03-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0009_remove_menu_in_cart_remove_menu_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='item_category',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], default='lunch', max_length=20),
        ),
    ]
