# Generated by Django 5.2.6 on 2026-03-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0010_menu_item_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='menu',
            name='item_category',
        ),
        migrations.AddField(
            model_name='menu',
            name='item_category',
            field=models.ManyToManyField(to='Menu.category'),
        ),
    ]
